"""init

Revision ID: b2dc1bb1e164
Revises: 
Create Date: 2025-12-14 17:04:48.993631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2dc1bb1e164'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('hashed_pwd', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('hashed_pwd')
    )
    op.create_table('todolist',
    sa.Column('taskid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=True),
    sa.Column('task_status', sa.String(length=10), nullable=True),
    sa.Column('user_state', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('taskid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todolist')
    op.drop_table('users')
    # ### end Alembic commands ###
